{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 0,
  "build_id": "v0.107.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "STONE_HUMIDIFIER",
                "title": {
                  "key": "STONE_HUMIDIFIER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "WINGED_BOOTS",
                "title": {
                  "key": "WINGED_BOOTS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "HEFTY_TABLET",
                "title": {
                  "key": "HEFTY_TABLET.title",
                  "table": "relics"
                },
                "was_chosen": true
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CREATIVE_AI"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLANT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HYPERBEAM"
              },
              {
                "id": "CARD.INJURY"
              }
            ],
            "current_gold": 99,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "HEFTY_TABLET.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 75,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.HEFTY_TABLET",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.FTL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.OVERCLOCK"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BALL_LIGHTNING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FTL"
              }
            ],
            "current_gold": 113,
            "current_hp": 69,
            "damage_taken": 6,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.GUNK_UP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TESLA_COIL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.COOLHEADED"
              }
            ],
            "current_gold": 125,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.CHARGE_BATTERY"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HOLOGRAM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.CHARGE_BATTERY"
              }
            ],
            "current_gold": 141,
            "current_hp": 67,
            "damage_taken": 2,
            "gold_gained": 16,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.GREED"
              }
            ],
            "current_gold": 467,
            "current_hp": 67,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SUNKEN_TREASURY.pages.INITIAL.options.SECOND_CHEST.title",
                  "table": "events"
                },
                "variables": {
                  "SmallChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 52,
                    "bool_value": false,
                    "string_value": null
                  },
                  "LargeChestGold": {
                    "type": "BaseDynamic",
                    "decimal_value": 326,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 326,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.SUNKEN_TREASURY",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.WHITE_NOISE"
              }
            ],
            "current_gold": 477,
            "current_hp": 67,
            "damage_taken": 0,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_NORMAL",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 1
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 477,
            "current_hp": 67,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.HYPERBEAM"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SKIM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FERAL"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MOMENTUM_STRIKE"
              }
            ],
            "current_gold": 517,
            "current_hp": 33,
            "damage_taken": 34,
            "gold_gained": 40,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_PREPARATION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 517,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 564,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 47,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.POTION_BELT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.ROCKET_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHADOW_SHIELD"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRASH_TO_TREASURE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ROCKET_PUNCH"
              }
            ],
            "current_gold": 584,
            "current_hp": 55,
            "damage_taken": 0,
            "gold_gained": 20,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.RADIANT_TINCTURE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CULTISTS_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.DAMP_CULTIST"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 584,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.BEAM_CELL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BEAM_CELL"
              }
            ],
            "current_gold": 619,
            "current_hp": 62,
            "damage_taken": 13,
            "gold_gained": 35,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FESTIVE_POPPER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "current_gold": 619,
            "current_hp": 62,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "THE_LEGENDS_WERE_TRUE.pages.INITIAL.options.NAB_THE_MAP.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.THE_LEGENDS_WERE_TRUE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.COLD_SNAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOMENTUM_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SWEEPING_BEAM"
              }
            ],
            "current_gold": 633,
            "current_hp": 50,
            "damage_taken": 12,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 633,
            "current_hp": 72,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 22,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 17,
                  "id": "CARD.MACHINE_LEARNING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.METEOR_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.VOLTAIC"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.MACHINE_LEARNING"
              }
            ],
            "current_gold": 733,
            "current_hp": 16,
            "damage_taken": 56,
            "gold_gained": 100,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.DEXTERITY_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.WATERFALL_GIANT_BOSS",
            "monster_ids": [
              "MONSTER.WATERFALL_GIANT"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "YUMMY_COOKIE",
                "title": {
                  "key": "YUMMY_COOKIE.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "STORYBOOK",
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SEAL_OF_GOLD",
                "title": {
                  "key": "SEAL_OF_GOLD.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BRIGHTEST_FLAME"
              }
            ],
            "current_gold": 733,
            "current_hp": 75,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STORYBOOK.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 59,
            "max_hp": 75,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.STORYBOOK",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TEZCATARA",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 19,
                  "id": "CARD.GO_FOR_THE_EYES"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SYNTHESIS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FUSION"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.GO_FOR_THE_EYES"
              }
            ],
            "current_gold": 746,
            "current_hp": 63,
            "damage_taken": 12,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TUNNELER_WEAK",
            "monster_ids": [
              "MONSTER.TUNNELER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.HORN_CLEAT",
              "RELIC.VAJRA"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LEAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WHITE_NOISE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAILSTORM"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DRAMATIC_ENTRANCE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ALCHEMIZE"
                },
                "was_picked": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.INJURY"
              }
            ],
            "current_gold": 266,
            "current_hp": 63,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 480,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 74,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLESSING_OF_THE_FORGE",
                "was_picked": false
              },
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.BEETLE_JUICE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.HORN_CLEAT",
                "was_picked": true
              },
              {
                "choice": "RELIC.VAJRA",
                "was_picked": true
              },
              {
                "choice": "RELIC.DINGY_RUG",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 21,
                  "id": "CARD.LEAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.HOTFIX"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COMPILE_DRIVER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.ROCKET_PUNCH"
              },
              {
                "current_upgrade_level": 1,
                "id": "CARD.LEAP"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 11,
                "id": "CARD.ROCKET_PUNCH"
              }
            ],
            "current_gold": 285,
            "current_hp": 56,
            "damage_taken": 7,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THIEVING_HOPPER_WEAK",
            "monster_ids": [
              "MONSTER.THIEVING_HOPPER"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.DARK_SHACKLES"
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.FTL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SYNCHRONIZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MULTI_CAST"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.LOOP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BEAM_CELL"
              },
              {
                "id": "CARD.DARK_SHACKLES"
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_DEFECT"
              }
            ],
            "current_gold": 73,
            "current_hp": 56,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 212,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.TOUCH_OF_INSANITY",
                "was_picked": false
              },
              {
                "choice": "POTION.BOTTLED_POTENTIAL",
                "was_picked": false
              },
              {
                "choice": "POTION.ATTACK_POTION",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GREMLIN_HORN",
                "was_picked": false
              },
              {
                "choice": "RELIC.JUZU_BRACELET",
                "was_picked": false
              },
              {
                "choice": "RELIC.SCREAMING_FLAGON",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 23,
                  "id": "CARD.LIGHTNING_ROD"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COOLHEADED"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.LIGHTNING_ROD"
              }
            ],
            "current_gold": 92,
            "current_hp": 48,
            "damage_taken": 8,
            "gold_gained": 19,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_NORMAL",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG",
              "MONSTER.BOWLBUG_SILK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 92,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 73,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 92,
            "current_hp": 79,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "STONE_OF_ALL_TIME.pages.INITIAL.options.LIFT.title",
                  "table": "events"
                },
                "variables": {
                  "DrinkRandomPotion": {
                    "type": "DynamicString",
                    "decimal_value": 0,
                    "bool_value": false,
                    "string_value": "Vulnerable Potion"
                  },
                  "DrinkMaxHpGain": {
                    "type": "BaseDynamic",
                    "decimal_value": 10,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PushHpLoss": {
                    "type": "BaseDynamic",
                    "decimal_value": 6,
                    "bool_value": false,
                    "string_value": null
                  },
                  "PushVigorousAmount": {
                    "type": "BaseDynamic",
                    "decimal_value": 8,
                    "bool_value": false,
                    "string_value": null
                  }
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 83,
            "max_hp_gained": 10,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_discarded": [
              "POTION.VULNERABLE_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.STONE_OF_ALL_TIME",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "cards_removed": [
              {
                "floor_added_to_deck": 14,
                "id": "CARD.SPOILS_MAP",
                "props": {
                  "ints": [
                    {
                      "name": "SpoilsActIndex",
                      "value": 1
                    }
                  ]
                }
              }
            ],
            "completed_quests": [
              "CARD.SPOILS_MAP"
            ],
            "current_gold": 737,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 645,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 83,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LUCKY_FYSH",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 737,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 83,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.GO_FOR_THE_EYES"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 28,
                  "id": "CARD.SIGNAL_BOOST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SYNCHRONIZE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FOCUSED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SIGNAL_BOOST"
              }
            ],
            "current_gold": 791,
            "current_hp": 66,
            "damage_taken": 13,
            "gold_gained": 54,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.REGAL_PILLOW",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.INFESTED_PRISMS_ELITE",
            "monster_ids": [
              "MONSTER.INFESTED_PRISM"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 791,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.BRIGHTEST_FLAME"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "cards_gained": [
              {
                "id": "CARD.CHARGE_BATTERY"
              },
              {
                "id": "CARD.HOLOGRAM"
              }
            ],
            "current_gold": 821,
            "current_hp": 66,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "ROOM_FULL_OF_CHEESE.pages.INITIAL.options.GORGE.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 30,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 82,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ROOM_FULL_OF_CHEESE",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 31,
                  "id": "CARD.SWEEPING_BEAM"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UPROAR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.GLACIER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SWEEPING_BEAM"
              }
            ],
            "current_gold": 873,
            "current_hp": 66,
            "damage_taken": 0,
            "gold_gained": 52,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.RED_MASK",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DECIMILLIPEDE_ELITE",
            "monster_ids": [
              "MONSTER.DECIMILLIPEDE_SEGMENT_FRONT",
              "MONSTER.DECIMILLIPEDE_SEGMENT_MIDDLE",
              "MONSTER.DECIMILLIPEDE_SEGMENT_BACK"
            ],
            "room_type": "elite",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 873,
            "current_hp": 81,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 15,
            "max_hp": 81,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 873,
            "current_hp": 0,
            "damage_taken": 81,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 1,
            "player_id": 1,
            "potion_used": [
              "POTION.FLEX_POTION",
              "POTION.RADIANT_TINCTURE",
              "POTION.EXPLOSIVE_AMPOULE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.KNOWLEDGE_DEMON_BOSS",
            "monster_ids": [
              "MONSTER.KNOWLEDGE_DEMON"
            ],
            "room_type": "boss",
            "turns_taken": 11
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "ELITE",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.DEFECT",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_DEFECT"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ZAP"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DUALCAST"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.HYPERBEAM"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.FTL"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.COOLHEADED"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.CHARGE_BATTERY"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.GREED"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.WHITE_NOISE"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.MOMENTUM_STRIKE"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.BEAM_CELL"
        },
        {
          "floor_added_to_deck": 15,
          "id": "CARD.SWEEPING_BEAM"
        },
        {
          "floor_added_to_deck": 17,
          "id": "CARD.MACHINE_LEARNING"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 18,
          "id": "CARD.BRIGHTEST_FLAME"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.GO_FOR_THE_EYES"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.ROCKET_PUNCH"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 21,
          "id": "CARD.LEAP"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.BEAM_CELL"
        },
        {
          "floor_added_to_deck": 22,
          "id": "CARD.DARK_SHACKLES"
        },
        {
          "floor_added_to_deck": 23,
          "id": "CARD.LIGHTNING_ROD"
        },
        {
          "floor_added_to_deck": 28,
          "id": "CARD.SIGNAL_BOOST"
        },
        {
          "floor_added_to_deck": 30,
          "id": "CARD.CHARGE_BATTERY"
        },
        {
          "floor_added_to_deck": 30,
          "id": "CARD.HOLOGRAM"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.SWEEPING_BEAM"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 5,
      "potions": [
        {
          "id": "POTION.GAMBLERS_BREW",
          "slot_index": 4
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.CRACKED_CORE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.HEFTY_TABLET"
        },
        {
          "floor_added_to_deck": 8,
          "id": "RELIC.BAG_OF_PREPARATION"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.POTION_BELT"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.FESTIVE_POPPER"
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.STORYBOOK"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.HORN_CLEAT"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.VAJRA"
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.LUCKY_FYSH"
        },
        {
          "floor_added_to_deck": 28,
          "id": "RELIC.REGAL_PILLOW"
        },
        {
          "floor_added_to_deck": 31,
          "id": "RELIC.RED_MASK"
        }
      ]
    }
  ],
  "run_time": 3017,
  "schema_version": 9,
  "seed": "WTZW2WE91V",
  "start_time": 1787288807,
  "was_abandoned": false,
  "win": false
}