{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 4,
  "build_id": "v0.107.1",
  "game_mode": "standard",
  "killed_by_encounter": "NONE.NONE",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PRECISE_SCISSORS",
                "title": {
                  "key": "PRECISE_SCISSORS.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "BOOMING_CONCH",
                "title": {
                  "key": "BOOMING_CONCH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SILVER_CRUCIBLE",
                "title": {
                  "key": "SILVER_CRUCIBLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "cards_removed": [
              {
                "floor_added_to_deck": 1,
                "id": "CARD.STRIKE_IRONCLAD"
              }
            ],
            "current_gold": 99,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PRECISE_SCISSORS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PRECISE_SCISSORS",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.UNRELENTING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.UNRELENTING"
              }
            ],
            "current_gold": 113,
            "current_hp": 64,
            "damage_taken": 6,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.TAUNT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TAUNT"
              }
            ],
            "current_gold": 121,
            "current_hp": 68,
            "damage_taken": 2,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.BATTLE_TRANCE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BATTLE_TRANCE"
              }
            ],
            "current_gold": 132,
            "current_hp": 70,
            "damage_taken": 4,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PERFECTED_STRIKE"
              }
            ],
            "current_gold": 140,
            "current_hp": 56,
            "damage_taken": 20,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_NORMAL",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.JUGGLING"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ASHEN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.JUGGLING"
              }
            ],
            "current_gold": 150,
            "current_hp": 60,
            "damage_taken": 2,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CULTISTS_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.DAMP_CULTIST"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 150,
            "current_hp": 60,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.PERFECTED_STRIKE"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.TREMBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TREMBLE"
              }
            ],
            "current_gold": 159,
            "current_hp": 59,
            "damage_taken": 7,
            "gold_gained": 9,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_NORMAL",
            "monster_ids": [
              "MONSTER.CALCIFIED_CULTIST",
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 9,
                  "id": "CARD.BLOOD_WALL"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SECOND_WIND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.UPPERCUT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLOOD_WALL"
              }
            ],
            "current_gold": 172,
            "current_hp": 61,
            "damage_taken": 4,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.LIQUID_BRONZE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LIVING_FOG_NORMAL",
            "monster_ids": [
              "MONSTER.LIVING_FOG",
              "MONSTER.GAS_BOMB"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 203,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 31,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.MEAT_ON_THE_BONE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 11,
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.ASHEN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.THUNDERCLAP"
              }
            ],
            "current_gold": 231,
            "current_hp": 48,
            "damage_taken": 31,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POTION_OF_BINDING"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.MOLTEN_EGG",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 231,
            "current_hp": 72,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.ONE_TWO_PUNCH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DRUM_OF_BATTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.ONE_TWO_PUNCH"
              }
            ],
            "current_gold": 259,
            "current_hp": 55,
            "damage_taken": 23,
            "gold_gained": 28,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.COLORLESS_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.VULNERABLE_POTION"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.PENDULUM",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SKULKING_COLONY_ELITE",
            "monster_ids": [
              "MONSTER.SKULKING_COLONY"
            ],
            "room_type": "elite",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.RUPTURE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.RUPTURE"
              }
            ],
            "current_gold": 272,
            "current_hp": 60,
            "damage_taken": 1,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.DEXTERITY_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.COLORLESS_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TWO_TAILED_RATS_NORMAL",
            "monster_ids": [
              "MONSTER.TWO_TAILED_RAT",
              "MONSTER.TWO_TAILED_RAT",
              "MONSTER.TWO_TAILED_RAT"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 15,
                  "id": "CARD.EXPECT_A_FIGHT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.VICIOUS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.EXPECT_A_FIGHT"
              }
            ],
            "current_gold": 279,
            "current_hp": 51,
            "damage_taken": 15,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.HAUNTED_SHIP_NORMAL",
            "monster_ids": [
              "MONSTER.HAUNTED_SHIP"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 279,
            "current_hp": 75,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 17,
                  "id": "CARD.TEAR_ASUNDER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.DARK_EMBRACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.CASCADE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.TEAR_ASUNDER"
              }
            ],
            "current_gold": 354,
            "current_hp": 48,
            "damage_taken": 33,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.LIQUID_BRONZE",
              "POTION.DEXTERITY_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LAGAVULIN_MATRIARCH_BOSS",
            "monster_ids": [
              "MONSTER.LAGAVULIN_MATRIARCH"
            ],
            "room_type": "boss",
            "turns_taken": 8
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "PAELS_FLESH",
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "PAELS_GROWTH",
                "title": {
                  "key": "PAELS_GROWTH.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "PAELS_EYE",
                "title": {
                  "key": "PAELS_EYE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 354,
            "current_hp": 73,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "PAELS_FLESH.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.PAELS_FLESH",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.PAEL",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 19,
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SETUP_STRIKE"
              }
            ],
            "current_gold": 362,
            "current_hp": 72,
            "damage_taken": 7,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_WEAK",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_colorless": [
              "CARD.PREP_TIME"
            ],
            "bought_relics": [
              "RELIC.NUNCHAKU"
            ],
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.DARK_EMBRACE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.IRON_WAVE"
              },
              {
                "id": "CARD.PREP_TIME"
              }
            ],
            "current_gold": 27,
            "current_hp": 72,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 335,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.WEAK_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.EXPLOSIVE_AMPOULE",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.NUNCHAKU",
                "was_picked": true
              },
              {
                "choice": "RELIC.PAPER_PHROG",
                "was_picked": false
              },
              {
                "choice": "RELIC.DRAGON_FRUIT",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 21,
                  "id": "CARD.INFLAME"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.INFLAME"
              }
            ],
            "current_gold": 41,
            "current_hp": 61,
            "damage_taken": 17,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FRUIT_JUICE",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.BOWLBUGS_WEAK",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 22,
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.IRON_WAVE"
              }
            ],
            "current_gold": 53,
            "current_hp": 58,
            "damage_taken": 21,
            "gold_gained": 12,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.MYTES_NORMAL",
            "monster_ids": [
              "MONSTER.MYTE",
              "MONSTER.MYTE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 23,
                  "id": "CARD.DOMINATE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TAUNT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.DOMINATE"
              }
            ],
            "current_gold": 63,
            "current_hp": 55,
            "damage_taken": 26,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 23,
            "max_hp": 85,
            "max_hp_gained": 5,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.FRUIT_JUICE"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_OBSCURA_NORMAL",
            "monster_ids": [
              "MONSTER.THE_OBSCURA",
              "MONSTER.PARAFRIGHT"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 24,
                  "id": "CARD.HELLRAISER"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BLOODLETTING"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.HELLRAISER"
              }
            ],
            "current_gold": 78,
            "current_hp": 37,
            "damage_taken": 36,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLUMBERING_BEETLE_NORMAL",
            "monster_ids": [
              "MONSTER.BOWLBUG_ROCK",
              "MONSTER.BOWLBUG_SILK",
              "MONSTER.SLUMBERING_BEETLE"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 78,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 116,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 38,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.VEXING_PUZZLEBOX",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 116,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.ONE_TWO_PUNCH"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 28,
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PERFECTED_STRIKE"
              }
            ],
            "current_gold": 124,
            "current_hp": 60,
            "damage_taken": 20,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.POWER_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SPINY_TOAD_NORMAL",
            "monster_ids": [
              "MONSTER.SPINY_TOAD"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 124,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 25,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 30,
                  "id": "CARD.INFERNO"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.DISMANTLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BLUDGEON"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.INFERNO"
              }
            ],
            "current_gold": 137,
            "current_hp": 85,
            "damage_taken": 4,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 4,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.OVICOPTER_NORMAL",
            "monster_ids": [
              "MONSTER.OVICOPTER",
              "MONSTER.TOUGH_EGG"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 31,
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FORGOTTEN_RITUAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.RAMPAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.HEADBUTT"
              }
            ],
            "current_gold": 152,
            "current_hp": 85,
            "damage_taken": 2,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 2,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.SKILL_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.EXOSKELETONS_NORMAL",
            "monster_ids": [
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON",
              "MONSTER.EXOSKELETON"
            ],
            "room_type": "monster",
            "turns_taken": 2
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 152,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.EXPECT_A_FIGHT"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 33,
                  "id": "CARD.PYRE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.TEAR_ASUNDER"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.PACTS_END"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PYRE"
              }
            ],
            "current_gold": 227,
            "current_hp": 61,
            "damage_taken": 30,
            "gold_gained": 75,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.VULNERABLE_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.STRENGTH_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_INSATIABLE_BOSS",
            "monster_ids": [
              "MONSTER.THE_INSATIABLE"
            ],
            "room_type": "boss",
            "turns_taken": 4
          }
        ]
      }
    ],
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "SPIKED_GAUNTLETS",
                "title": {
                  "key": "SPIKED_GAUNTLETS.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "IRON_CLUB",
                "title": {
                  "key": "IRON_CLUB.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "THROWING_AXE",
                "title": {
                  "key": "THROWING_AXE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 227,
            "current_hp": 80,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "SPIKED_GAUNTLETS.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 19,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.SPIKED_GAUNTLETS",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.TANX",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 35,
                  "id": "CARD.SWORD_BOOMERANG"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.CINDER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SWORD_BOOMERANG"
              }
            ],
            "current_gold": 242,
            "current_hp": 69,
            "damage_taken": 17,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TURRET_OPERATOR_WEAK",
            "monster_ids": [
              "MONSTER.LIVING_SHIELD",
              "MONSTER.TURRET_OPERATOR"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 36,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.EVIL_EYE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.SHRUG_IT_OFF"
              }
            ],
            "current_gold": 250,
            "current_hp": 51,
            "damage_taken": 24,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ENTROPIC_BREW",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.DEVOTED_SCULPTOR_WEAK",
            "monster_ids": [
              "MONSTER.DEVOTED_SCULPTOR"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "bought_relics": [
              "RELIC.SPARKLING_ROUGE"
            ],
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BULLY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BURNING_PACT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.TRUE_GRIT"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.INFLAME"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FINESSE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.BOLAS"
                },
                "was_picked": false
              }
            ],
            "current_gold": 17,
            "current_hp": 51,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 233,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.FLEX_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.POTION_OF_BINDING",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.SPARKLING_ROUGE",
                "was_picked": true
              },
              {
                "choice": "RELIC.GORGET",
                "was_picked": false
              },
              {
                "choice": "RELIC.KIFUDA",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 38,
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.HOWL_FROM_BEYOND"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HELLRAISER"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.MOLTEN_FIST"
              }
            ],
            "current_gold": 25,
            "current_hp": 34,
            "damage_taken": 35,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 85,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.BLOCK_POTION",
                "was_picked": true
              },
              {
                "choice": "POTION.STRENGTH_POTION",
                "was_picked": true
              }
            ],
            "potion_used": [
              "POTION.VULNERABLE_POTION",
              "POTION.ENTROPIC_BREW",
              "POTION.BLOCK_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SLIMED_BERSERKER_NORMAL",
            "monster_ids": [
              "MONSTER.SLIMED_BERSERKER"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 25,
            "current_hp": 54,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "HUNGRY_FOR_MUSHROOMS.pages.INITIAL.options.BIG_MUSHROOM.title",
                  "table": "events"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 20,
            "max_hp": 105,
            "max_hp_gained": 20,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.BIG_MUSHROOM",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.HUNGRY_FOR_MUSHROOMS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 25,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 31,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 58,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 33,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.HAPPY_FLOWER",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 58,
            "current_hp": 85,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.HELLRAISER"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 43,
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.ARMAMENTS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.PERFECTED_STRIKE"
              }
            ],
            "current_gold": 73,
            "current_hp": 61,
            "damage_taken": 42,
            "gold_gained": 15,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.THE_LOST_AND_FORGOTTEN_NORMAL",
            "monster_ids": [
              "MONSTER.THE_LOST",
              "MONSTER.THE_FORGOTTEN"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 73,
            "current_hp": 92,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 31,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 45,
                  "id": "CARD.UPPERCUT"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.STONE_ARMOR"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.BATTLE_TRANCE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.UPPERCUT"
              }
            ],
            "current_gold": 81,
            "current_hp": 69,
            "damage_taken": 41,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CONSTRUCT_MENAGERIE_NORMAL",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT",
              "MONSTER.CUBEX_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "current_upgrade_level": 1,
                  "floor_added_to_deck": 46,
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": true
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.UNRELENTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "current_upgrade_level": 1,
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "current_upgrade_level": 1,
                "id": "CARD.MOLTEN_FIST"
              }
            ],
            "current_gold": 95,
            "current_hp": 60,
            "damage_taken": 27,
            "gold_gained": 14,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FIRE_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FROG_KNIGHT_NORMAL",
            "monster_ids": [
              "MONSTER.FROG_KNIGHT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 95,
            "current_hp": 91,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 31,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 95,
            "current_hp": 44,
            "damage_taken": 65,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 18,
            "max_hp": 105,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.STRENGTH_POTION",
              "POTION.FIRE_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TEST_SUBJECT_BOSS",
            "monster_ids": [
              "MONSTER.TEST_SUBJECT"
            ],
            "room_type": "boss",
            "turns_taken": 6
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [
        {
          "id": "GLUTTON",
          "rarity": "bronze"
        }
      ],
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.UNRELENTING"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.TAUNT"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.BATTLE_TRANCE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.PERFECTED_STRIKE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.JUGGLING"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.TREMBLE"
        },
        {
          "floor_added_to_deck": 9,
          "id": "CARD.BLOOD_WALL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 11,
          "id": "CARD.THUNDERCLAP"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 13,
          "id": "CARD.ONE_TWO_PUNCH"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.RUPTURE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 15,
          "id": "CARD.EXPECT_A_FIGHT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 17,
          "id": "CARD.TEAR_ASUNDER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 19,
          "id": "CARD.SETUP_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 20,
          "id": "CARD.IRON_WAVE"
        },
        {
          "floor_added_to_deck": 20,
          "id": "CARD.PREP_TIME"
        },
        {
          "floor_added_to_deck": 21,
          "id": "CARD.INFLAME"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 22,
          "id": "CARD.IRON_WAVE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 23,
          "id": "CARD.DOMINATE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 24,
          "id": "CARD.HELLRAISER"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 28,
          "id": "CARD.PERFECTED_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 30,
          "id": "CARD.INFERNO"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 31,
          "id": "CARD.HEADBUTT"
        },
        {
          "floor_added_to_deck": 33,
          "id": "CARD.PYRE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 35,
          "id": "CARD.SWORD_BOOMERANG"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 36,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 38,
          "id": "CARD.MOLTEN_FIST"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 43,
          "id": "CARD.PERFECTED_STRIKE"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 45,
          "id": "CARD.UPPERCUT"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 46,
          "id": "CARD.MOLTEN_FIST"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.PRECISE_SCISSORS"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.MEAT_ON_THE_BONE"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.MOLTEN_EGG"
        },
        {
          "floor_added_to_deck": 13,
          "id": "RELIC.PENDULUM",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 1
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 18,
          "id": "RELIC.PAELS_FLESH"
        },
        {
          "floor_added_to_deck": 20,
          "id": "RELIC.NUNCHAKU",
          "props": {
            "ints": [
              {
                "name": "AttacksPlayed",
                "value": 125
              }
            ]
          }
        },
        {
          "floor_added_to_deck": 26,
          "id": "RELIC.VEXING_PUZZLEBOX"
        },
        {
          "floor_added_to_deck": 34,
          "id": "RELIC.SPIKED_GAUNTLETS"
        },
        {
          "floor_added_to_deck": 37,
          "id": "RELIC.SPARKLING_ROUGE"
        },
        {
          "floor_added_to_deck": 39,
          "id": "RELIC.BIG_MUSHROOM"
        },
        {
          "floor_added_to_deck": 41,
          "id": "RELIC.HAPPY_FLOWER",
          "props": {
            "ints": [
              {
                "name": "TurnsSeen",
                "value": 2
              }
            ]
          }
        }
      ]
    }
  ],
  "run_time": 3092,
  "schema_version": 9,
  "seed": "544N9441ZH",
  "start_time": 1787902869,
  "was_abandoned": false,
  "win": true
}