{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 8,
  "build_id": "v0.107.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.LAGAVULIN_MATRIARCH_BOSS",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "LOST_COFFER",
                "title": {
                  "key": "LOST_COFFER.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "LEAD_PAPERWEIGHT",
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "SILVER_CRUCIBLE",
                "title": {
                  "key": "SILVER_CRUCIBLE.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "card_choices": [
              {
                "card": {
                  "id": "CARD.THRUMMING_HATCHET"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.FINESSE"
              }
            ],
            "current_gold": 99,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "LEAD_PAPERWEIGHT.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.LEAD_PAPERWEIGHT",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.BREAKTHROUGH"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TREMBLE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.COLOSSUS"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BREAKTHROUGH"
              }
            ],
            "current_gold": 112,
            "current_hp": 64,
            "damage_taken": 6,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.BULLY"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.WHIRLWIND"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.IRON_WAVE"
              }
            ],
            "current_gold": 120,
            "current_hp": 61,
            "damage_taken": 9,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "shop",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "id": "CARD.CONFLAGRATION"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.STOMP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FISTICUFFS"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MAYHEM"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.BLOODLETTING"
              },
              {
                "id": "CARD.BLOOD_WALL"
              }
            ],
            "current_gold": 45,
            "current_hp": 61,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 75,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.POWER_POTION",
                "was_picked": false
              },
              {
                "choice": "POTION.LIQUID_MEMORIES",
                "was_picked": false
              },
              {
                "choice": "POTION.HEART_OF_IRON",
                "was_picked": false
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.LETTER_OPENER",
                "was_picked": false
              },
              {
                "choice": "RELIC.PLANISPHERE",
                "was_picked": false
              },
              {
                "choice": "RELIC.SCREAMING_FLAGON",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "shop",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.INFERNO"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PILLAGE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.INFERNO"
              }
            ],
            "current_gold": 53,
            "current_hp": 61,
            "damage_taken": 6,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.INFERNO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.FEEL_NO_PAIN"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TWIN_STRIKE"
              }
            ],
            "current_gold": 63,
            "current_hp": 55,
            "damage_taken": 12,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PUNCH_CONSTRUCT_NORMAL",
            "monster_ids": [
              "MONSTER.PUNCH_CONSTRUCT"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 63,
            "current_hp": 79,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 24,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 8,
                  "id": "CARD.WHIRLWIND"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.TWIN_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.IRON_WAVE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.WHIRLWIND"
              }
            ],
            "current_gold": 74,
            "current_hp": 62,
            "damage_taken": 23,
            "gold_gained": 11,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.GREMLIN_MERC_NORMAL",
            "monster_ids": [
              "MONSTER.GREMLIN_MERC",
              "MONSTER.SNEAKY_GREMLIN",
              "MONSTER.FAT_GREMLIN"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 74,
            "current_hp": 62,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "SMITH"
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.INFERNO"
            ]
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "treasure",
        "player_stats": [
          {
            "current_gold": 110,
            "current_hp": 69,
            "damage_taken": 0,
            "gold_gained": 36,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 7,
            "max_hp": 87,
            "max_hp_gained": 7,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.STRAWBERRY",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "treasure",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 11,
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.THUNDERCLAP"
              }
            ],
            "current_gold": 137,
            "current_hp": 44,
            "damage_taken": 31,
            "gold_gained": 27,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 87,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.GAMBLERS_BREW",
                "was_picked": true
              }
            ],
            "relic_choices": [
              {
                "choice": "RELIC.GREMLIN_HORN",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.PHANTASMAL_GARDENERS_ELITE",
            "monster_ids": [
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER",
              "MONSTER.PHANTASMAL_GARDENER"
            ],
            "room_type": "elite",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 137,
            "current_hp": 70,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 26,
            "max_hp": 87,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 13,
                  "id": "CARD.SPITE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.PERFECTED_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SPITE"
              }
            ],
            "current_gold": 150,
            "current_hp": 63,
            "damage_taken": 13,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 87,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.REGEN_POTION",
                "was_picked": true
              }
            ],
            "potion_discarded": [
              "POTION.GAMBLERS_BREW"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LIVING_FOG_NORMAL",
            "monster_ids": [
              "MONSTER.LIVING_FOG",
              "MONSTER.GAS_BOMB"
            ],
            "room_type": "monster",
            "turns_taken": 3
          }
        ]
      },
      {
        "map_point_type": "elite",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 14,
                  "id": "CARD.PILLAGE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.INFERNO"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.THUNDERCLAP"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.PILLAGE"
              }
            ],
            "current_gold": 182,
            "current_hp": 62,
            "damage_taken": 22,
            "gold_gained": 32,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 21,
            "max_hp": 87,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.REGEN_POTION",
              "POTION.GAMBLERS_BREW"
            ],
            "relic_choices": [
              {
                "choice": "RELIC.BAG_OF_MARBLES",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TERROR_EEL_ELITE",
            "monster_ids": [
              "MONSTER.TERROR_EEL"
            ],
            "room_type": "elite",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "current_gold": 182,
            "current_hp": 47,
            "damage_taken": 25,
            "event_choices": [
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.INITIAL.options.IMMERSE.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.LINGER.title",
                  "table": "events"
                },
                "variables": {}
              },
              {
                "title": {
                  "key": "ABYSSAL_BATHS.pages.ALL.options.EXIT_BATHS.title",
                  "table": "events"
                },
                "variables": {}
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 10,
            "max_hp": 97,
            "max_hp_gained": 10,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.ABYSSAL_BATHS",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "rest_site",
        "player_stats": [
          {
            "current_gold": 182,
            "current_hp": 76,
            "damage_taken": 0,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 29,
            "max_hp": 97,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "rest_site_choices": [
              "HEAL"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "room_type": "rest_site",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "boss",
        "player_stats": [
          {
            "current_gold": 182,
            "current_hp": 0,
            "damage_taken": 76,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 97,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LAGAVULIN_MATRIARCH_BOSS",
            "monster_ids": [
              "MONSTER.LAGAVULIN_MATRIARCH"
            ],
            "room_type": "boss",
            "turns_taken": 10
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.FINESSE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.BREAKTHROUGH"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.IRON_WAVE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.BLOODLETTING"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.BLOOD_WALL"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 5,
          "id": "CARD.INFERNO"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.TWIN_STRIKE"
        },
        {
          "floor_added_to_deck": 8,
          "id": "CARD.WHIRLWIND"
        },
        {
          "floor_added_to_deck": 11,
          "id": "CARD.THUNDERCLAP"
        },
        {
          "floor_added_to_deck": 13,
          "id": "CARD.SPITE"
        },
        {
          "floor_added_to_deck": 14,
          "id": "CARD.PILLAGE"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.LEAD_PAPERWEIGHT"
        },
        {
          "floor_added_to_deck": 10,
          "id": "RELIC.STRAWBERRY"
        },
        {
          "floor_added_to_deck": 11,
          "id": "RELIC.GREMLIN_HORN"
        },
        {
          "floor_added_to_deck": 14,
          "id": "RELIC.BAG_OF_MARBLES"
        }
      ]
    }
  ],
  "run_time": 757,
  "schema_version": 9,
  "seed": "Z5Y8VJPTNG",
  "start_time": 1788947112,
  "was_abandoned": false,
  "win": false
}