{
  "acts": [
    "ACT.UNDERDOCKS",
    "ACT.HIVE",
    "ACT.GLORY"
  ],
  "ascension": 9,
  "build_id": "v0.107.1",
  "game_mode": "standard",
  "killed_by_encounter": "ENCOUNTER.FOSSIL_STALKER_NORMAL",
  "killed_by_event": "NONE.NONE",
  "map_point_history": [
    [
      {
        "map_point_type": "ancient",
        "player_stats": [
          {
            "ancient_choice": [
              {
                "TextKey": "FISHING_ROD",
                "title": {
                  "key": "FISHING_ROD.title",
                  "table": "relics"
                },
                "was_chosen": true
              },
              {
                "TextKey": "WINGED_BOOTS",
                "title": {
                  "key": "WINGED_BOOTS.title",
                  "table": "relics"
                },
                "was_chosen": false
              },
              {
                "TextKey": "SILKEN_TRESS",
                "title": {
                  "key": "SILKEN_TRESS.title",
                  "table": "relics"
                },
                "was_chosen": false
              }
            ],
            "current_gold": 99,
            "current_hp": 64,
            "damage_taken": 0,
            "event_choices": [
              {
                "title": {
                  "key": "FISHING_ROD.title",
                  "table": "relics"
                }
              }
            ],
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 64,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "relic_choices": [
              {
                "choice": "RELIC.FISHING_ROD",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "EVENT.NEOW",
            "room_type": "event",
            "turns_taken": 0
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 2,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.RAMPAGE"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HEADBUTT"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHRUG_IT_OFF"
              }
            ],
            "current_gold": 112,
            "current_hp": 58,
            "damage_taken": 12,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.SKILL_POTION",
                "was_picked": true
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TOADPOLES_WEAK",
            "monster_ids": [
              "MONSTER.TOADPOLE",
              "MONSTER.TOADPOLE"
            ],
            "room_type": "monster",
            "turns_taken": 4
          }
        ]
      },
      {
        "map_point_type": "unknown",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 3,
                  "id": "CARD.POMMEL_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.JUGGLING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.POMMEL_STRIKE"
              }
            ],
            "current_gold": 125,
            "current_hp": 40,
            "damage_taken": 24,
            "gold_gained": 13,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.SEAPUNK_WEAK",
            "monster_ids": [
              "MONSTER.SEAPUNK"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 4,
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.UNRELENTING"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.RUPTURE"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SHRUG_IT_OFF"
              }
            ],
            "current_gold": 135,
            "current_hp": 37,
            "damage_taken": 9,
            "gold_gained": 10,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.FYSH_OIL",
                "was_picked": true
              }
            ],
            "stolen_loot": 0,
            "upgraded_cards": [
              "CARD.STRIKE_IRONCLAD"
            ]
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.CORPSE_SLUGS_WEAK",
            "monster_ids": [
              "MONSTER.CORPSE_SLUG",
              "MONSTER.CORPSE_SLUG"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 5,
                  "id": "CARD.TREMBLE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.SHRUG_IT_OFF"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.MOLTEN_FIST"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.TREMBLE"
              }
            ],
            "current_gold": 143,
            "current_hp": 38,
            "damage_taken": 5,
            "gold_gained": 8,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_choices": [
              {
                "choice": "POTION.ENERGY_POTION",
                "was_picked": false
              }
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.LIVING_FOG_NORMAL",
            "monster_ids": [
              "MONSTER.LIVING_FOG",
              "MONSTER.GAS_BOMB"
            ],
            "room_type": "monster",
            "turns_taken": 7
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "card_choices": [
              {
                "card": {
                  "floor_added_to_deck": 6,
                  "id": "CARD.SETUP_STRIKE"
                },
                "was_picked": true
              },
              {
                "card": {
                  "id": "CARD.FORGOTTEN_RITUAL"
                },
                "was_picked": false
              },
              {
                "card": {
                  "id": "CARD.HAVOC"
                },
                "was_picked": false
              }
            ],
            "cards_gained": [
              {
                "id": "CARD.SETUP_STRIKE"
              }
            ],
            "current_gold": 150,
            "current_hp": 28,
            "damage_taken": 16,
            "gold_gained": 7,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 6,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "potion_used": [
              "POTION.SKILL_POTION"
            ],
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.TWO_TAILED_RATS_NORMAL",
            "monster_ids": [
              "MONSTER.TWO_TAILED_RAT",
              "MONSTER.TWO_TAILED_RAT",
              "MONSTER.TWO_TAILED_RAT"
            ],
            "room_type": "monster",
            "turns_taken": 6
          }
        ]
      },
      {
        "map_point_type": "monster",
        "player_stats": [
          {
            "current_gold": 150,
            "current_hp": 0,
            "damage_taken": 28,
            "gold_gained": 0,
            "gold_lost": 0,
            "gold_spent": 0,
            "gold_stolen": 0,
            "hp_healed": 0,
            "max_hp": 80,
            "max_hp_gained": 0,
            "max_hp_lost": 0,
            "player_id": 1,
            "stolen_loot": 0
          }
        ],
        "rooms": [
          {
            "model_id": "ENCOUNTER.FOSSIL_STALKER_NORMAL",
            "monster_ids": [
              "MONSTER.FOSSIL_STALKER"
            ],
            "room_type": "monster",
            "turns_taken": 5
          }
        ]
      }
    ]
  ],
  "modifiers": [],
  "platform_type": "steam",
  "players": [
    {
      "badges": [],
      "character": "CHARACTER.IRONCLAD",
      "deck": [
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "current_upgrade_level": 1,
          "floor_added_to_deck": 1,
          "id": "CARD.STRIKE_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.DEFEND_IRONCLAD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.BASH"
        },
        {
          "floor_added_to_deck": 1,
          "id": "CARD.ASCENDERS_BANE"
        },
        {
          "floor_added_to_deck": 2,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "floor_added_to_deck": 3,
          "id": "CARD.POMMEL_STRIKE"
        },
        {
          "floor_added_to_deck": 4,
          "id": "CARD.SHRUG_IT_OFF"
        },
        {
          "floor_added_to_deck": 5,
          "id": "CARD.TREMBLE"
        },
        {
          "floor_added_to_deck": 6,
          "id": "CARD.SETUP_STRIKE"
        }
      ],
      "id": 1,
      "max_potion_slot_count": 2,
      "potions": [
        {
          "id": "POTION.FYSH_OIL",
          "slot_index": 1
        }
      ],
      "relics": [
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.BURNING_BLOOD"
        },
        {
          "floor_added_to_deck": 1,
          "id": "RELIC.FISHING_ROD",
          "props": {
            "ints": [
              {
                "name": "CombatsSeen",
                "value": 5
              }
            ]
          }
        }
      ]
    }
  ],
  "run_time": 470,
  "schema_version": 9,
  "seed": "1FDF5VY7NA",
  "start_time": 1789045118,
  "was_abandoned": false,
  "win": false
}